category: ALARM
values:
  - aggregated values:
      priority: 40
      original values:
        - name: critical
          operational_value: CRITICAL
  - aggregated values:
      priority: 30
      original values:
        - name: moderate
          operational_value: SEVERE
  - aggregated values:
      priority: 20
      original values:
        - name: low
          operational_value: WARNING
  - aggregated values:
      priority: 20
      original values:
        - name: insufficient data
          operational_value: N/A
  - aggregated values:
      priority: 10
      original values:
        - name: OK
          operational_value: OK
        - name: UP
          operational_value: OK
