category: RESOURCE
values:
  - aggregated values:
      priority: 40
      original values:
        - name: ERROR
          operational_value: ERROR
        - name: ERROR_DELETING
          operational_value: ERROR
        - name: ERROR_RESTORING
          operational_value: ERROR
        - name: ERROR_EXTENDING
          operational_value: ERROR
  - aggregated values:
      priority: 30
      original values:
        - name: CREATING
          operational_value: TRANSIENT
        - name: ATTACHING
          operational_value: TRANSIENT
        - name: DELETING
          operational_value: TRANSIENT
        - name: RESTORING-BACKUP
          operational_value: TRANSIENT
        - name: BACKING-UP
          operational_value: TRANSIENT
        - name: DETACHING
          operational_value: TRANSIENT
  - aggregated values:
      priority: 20
      original values:
        - name: SUBOPTIMAL
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 10
      original values:
        - name: AVAILABLE
          operational_value: OK
        - name: IN-USE
          operational_value: OK
