category: ALARM
values:
  - aggregated values:
      priority: 40
      original values:
        - name: FAILURE
          operational_value: CRITICAL
  - aggregated values:
        priority: 30
        original values:
          - name: WARNING
            operational_value: WARNING
  - aggregated values:
      priority: 10
      original values:
        - name: OK
          operational_value: OK