category: ALARM
values:
  - aggregated values:
      priority: 40
      original values:
        - name: critical
          operational_value: CRITICAL
  - aggregated values:
      priority: 10
      original values:
        - name: OK
          operational_value: OK
