category: RESOURCE
values:
  - aggregated values:
      priority: 40
      original values:
        - name: DELETE_FAILED
          operational_value: ERROR
        - name: CREATE_FAILED
          operational_value: ERROR
        - name: UPDATE_FAILED
          operational_value: ERROR
        - name: RESUME_FAILED
          operational_value: ERROR
        - name: SUSPEND_FAILED
          operational_value: ERROR
  - aggregated values:
      priority: 30
      original values:
        - name: DELETE_IN_PROGRESS
          operational_value: TRANSIENT
        - name: CREATE_IN_PROGRESS
          operational_value: TRANSIENT
        - name: UPDATE_IN_PROGRESS
          operational_value: TRANSIENT
        - name: RESUME_IN_PROGRESS
          operational_value: TRANSIENT
        - name: SUSPEND_IN_PROGRESS
          operational_value: TRANSIENT
  - aggregated values:
      priority: 20
      original values:
        - name: SUBOPTIMAL
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 10
      original values:
        - name: DELETE_COMPLETE
          operational_value: OK
        - name: CREATE_COMPLETE
          operational_value: OK
        - name: UPDATE_COMPLETE
          operational_value: OK
        - name: RESUME_COMPLETE
          operational_value: OK
        - name: SUSPEND_COMPLETE
          operational_value: OK
