category: RESOURCE
values:
  - aggregated values:
      priority: 50
      original values:
        - name: ERROR
          operational_value: ERROR
  - aggregated values:
      priority: 40
      original values:
        - name: DOWN
          operational_value: ERROR
  - aggregated values:
      priority: 30
      original values:
        - name: BUILD
          operational_value: TRANSIENT
  - aggregated values:
      priority: 20
      original values:
        - name: SUBOPTIMAL
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 10
      original values:
        - name: ACTIVE
          operational_value: OK
