category: RESOURCE
values:
  - aggregated values:
      priority: 80
      original values:
        - name: DELETED
          operational_value: DELETED
        - name: HARD_DELETED
          operational_value: DELETED
        - name: SHELVED_OFFLOADED
          operational_value: DELETED
        - name: SOFT_DELETED
          operational_value: DELETED
  - aggregated values:
      priority: 70
      original values:
        - name: ERROR
          operational_value: ERROR
  - aggregated values:
      priority: 60
      original values:
        - name: SUSPENDED
          operational_value: SUBOPTIMAL
        - name: PAUSED
          operational_value: SUBOPTIMAL
        - name: STOPPED
          operational_value: SUBOPTIMAL
        - name: SHELVED
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 50
      original values:
        - name: RESIZED
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 40
      original values:
        - name: BUILDING
          operational_value: TRANSIENT
        - name: INITIALIZED
          operational_value: TRANSIENT
  - aggregated values:
      priority: 30
      original values:
        - name: SUBOPTIMAL
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 20
      original values:
        - name: RESCUED
          operational_value: OK
  - aggregated values:
      priority: 10
      original values:
        - name: ACTIVE
          operational_value: OK
