category: RESOURCE
values:
  - aggregated values:
      priority: 80
      original values:
        - name: DELETED
          operational_value: DELETED
  - aggregated values:
      priority: 70
      original values:
        - name: ERROR
          operational_value: ERROR
  - aggregated values:
      priority: 20
      original values:
        - name: SUBOPTIMAL
          operational_value: SUBOPTIMAL
  - aggregated values:
      priority: 10
      original values:
        - name: ACTIVE
          operational_value: OK
