category: ALARM
values:
  - aggregated values:
      priority: 50
      original values:
        - name: HIGH
          operational_value: CRITICAL
        - name: DISASTER
          operational_value: CRITICAL
  - aggregated values:
      priority: 40
      original values:
        - name: AVERAGE
          operational_value: SEVERE
  - aggregated values:
      priority: 30
      original values:
        - name: WARNING
          operational_value: WARNING
  - aggregated values:
      priority: 20
      original values:
        - name: NOT CLASSIFIED
          operational_value: N/A
  - aggregated values:
      priority: 10
      original values:
        - name: OK
          operational_value: OK
        - name: INFORMATION
          operational_value: OK
